export const errorMessage = {

Blank_Field : "Please enter Mobile Number.",
CountryCodeMobilenumberisnotmatch :"We do not recognize this mobile number. Please try again.",
UnregisteredMobileNumber : "We do not recognize this mobile number. Please try again.",
MobileNumberlessthan10digit : "Please enter valid mobile number.",
MobileNumberRequired : "Please enter mobile number.",
UserNameRequired : "Please enter username.",
PasswordRequired : "Please enter password.",
EmailRequired:"Please enter user name",
OTPsent : "We have sent 6-digit OTP.",
BlankOTP : "Please enter OTP.",
UserEnterlessthan6digitOTP : "Please enter valid OTP.",
Session : "Sorry, but your session has expired. Please try again.",
OTPattempts : "Please enter a valid OTP. You have 1 attempt left.",
Maxattemptsofresendbutton :"Please enter a valid OTP. You have 1 attempt left.",
SearchEvent :"The search result was not found.",
Listviewempty : "There are no records found.",
Mandatoryfield : "Please enter Product Name.",
CharacterLimit : "The product name should not exceed 255 characters in length.",
DuplicateData : "The product name already exists.",
Addbutton : "The product has been added successfully.",
Editbutton : "Product updated successfully.",
Deletebutton : "Are you sure you want to delete? Y/N . The product has been deleted successfully.",
InvalidEmail : "Please enter valid email.",
InvalidPin : "Please enter 6-digit valid pin.",
BlankDropdown : "Please select a store.",
Creationofpurchaseorder : "The purchase order has been created successfully.",
FutureDatenotallowed : "Please select a date that is not in the future.",
CostQuantity : "Please enter a value greater than 0 for the cost.",
AddPurchaseOrderCreatebutton : "Invoice must have at least 1 items.",
InvalidOTP : "Please enter valid OTP.",
UserLocked: "User has been locked.\nPlease login after some time."

}